# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\db_conn.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_db_conn_QWidget(object):
    def setupUi(self, db_conn_QWidget):
        db_conn_QWidget.setObjectName(_fromUtf8("db_conn_QWidget"))
        db_conn_QWidget.resize(280, 531)
        self.verticalLayout_2 = QtGui.QVBoxLayout(db_conn_QWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.DBConnection_dockable = QtGui.QDockWidget(db_conn_QWidget)
        self.DBConnection_dockable.setObjectName(_fromUtf8("DBConnection_dockable"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.dbconFile_GroupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.dbconFile_GroupBox.setObjectName(_fromUtf8("dbconFile_GroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dbconFile_GroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.confi_LoadFile_pushButton = QtGui.QPushButton(self.dbconFile_GroupBox)
        self.confi_LoadFile_pushButton.setObjectName(_fromUtf8("confi_LoadFile_pushButton"))
        self.horizontalLayout.addWidget(self.confi_LoadFile_pushButton)
        self.config_saveFile_PushButton = QtGui.QPushButton(self.dbconFile_GroupBox)
        self.config_saveFile_PushButton.setObjectName(_fromUtf8("config_saveFile_PushButton"))
        self.horizontalLayout.addWidget(self.config_saveFile_PushButton)
        self.config_filename_lineEdit = QtGui.QLineEdit(self.dbconFile_GroupBox)
        self.config_filename_lineEdit.setMaxLength(80)
        self.config_filename_lineEdit.setObjectName(_fromUtf8("config_filename_lineEdit"))
        self.horizontalLayout.addWidget(self.config_filename_lineEdit)
        self.verticalLayout.addWidget(self.dbconFile_GroupBox)
        self.connection_groupbox = QtGui.QGroupBox(self.dockWidgetContents)
        self.connection_groupbox.setObjectName(_fromUtf8("connection_groupbox"))
        self.dbconConnect_GroupBox = QtGui.QVBoxLayout(self.connection_groupbox)
        self.dbconConnect_GroupBox.setObjectName(_fromUtf8("dbconConnect_GroupBox"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.conn_host_label = QtGui.QLabel(self.connection_groupbox)
        self.conn_host_label.setObjectName(_fromUtf8("conn_host_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.conn_host_label)
        self.conn_host_lineEdit = QtGui.QLineEdit(self.connection_groupbox)
        self.conn_host_lineEdit.setObjectName(_fromUtf8("conn_host_lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.conn_host_lineEdit)
        self.conn_port_label = QtGui.QLabel(self.connection_groupbox)
        self.conn_port_label.setObjectName(_fromUtf8("conn_port_label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.conn_port_label)
        self.conn_port_lineEdit = QtGui.QLineEdit(self.connection_groupbox)
        self.conn_port_lineEdit.setObjectName(_fromUtf8("conn_port_lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.conn_port_lineEdit)
        self.conn_UserFile_labl = QtGui.QLabel(self.connection_groupbox)
        self.conn_UserFile_labl.setObjectName(_fromUtf8("conn_UserFile_labl"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.conn_UserFile_labl)
        self.conn_dbname_label = QtGui.QLabel(self.connection_groupbox)
        self.conn_dbname_label.setObjectName(_fromUtf8("conn_dbname_label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.conn_dbname_label)
        self.conn_userfilename_lineEdit = QtGui.QLineEdit(self.connection_groupbox)
        self.conn_userfilename_lineEdit.setObjectName(_fromUtf8("conn_userfilename_lineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.conn_userfilename_lineEdit)
        self.conn_dbname_lineEdit = QtGui.QLineEdit(self.connection_groupbox)
        self.conn_dbname_lineEdit.setObjectName(_fromUtf8("conn_dbname_lineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.conn_dbname_lineEdit)
        self.dbconConnect_GroupBox.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.connection_groupbox)
        self.socialtable_groupbox = QtGui.QGroupBox(self.dockWidgetContents)
        self.socialtable_groupbox.setObjectName(_fromUtf8("socialtable_groupbox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.socialtable_groupbox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.social_tablename_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_tablename_label.setObjectName(_fromUtf8("social_tablename_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.social_tablename_label)
        self.social_datacolumn_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_datacolumn_label.setObjectName(_fromUtf8("social_datacolumn_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.social_datacolumn_label)
        self.socia_data_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.socia_data_lineEdit.setObjectName(_fromUtf8("socia_data_lineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.socia_data_lineEdit)
        self.social_timecolum_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_timecolum_label.setObjectName(_fromUtf8("social_timecolum_label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.social_timecolum_label)
        self.social_time_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.social_time_lineEdit.setObjectName(_fromUtf8("social_time_lineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.social_time_lineEdit)
        self.social_usercolumn_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_usercolumn_label.setObjectName(_fromUtf8("social_usercolumn_label"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.social_usercolumn_label)
        self.social_user_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.social_user_lineEdit.setObjectName(_fromUtf8("social_user_lineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.social_user_lineEdit)
        self.social_geometrycoloumn_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_geometrycoloumn_label.setObjectName(_fromUtf8("social_geometrycoloumn_label"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.social_geometrycoloumn_label)
        self.social_geomtery_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.social_geomtery_lineEdit.setObjectName(_fromUtf8("social_geomtery_lineEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.social_geomtery_lineEdit)
        self.lineEdit_5 = QtGui.QLineEdit(self.socialtable_groupbox)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.socialtable_groupbox)
        self.areaboundarytable_groupbox = QtGui.QGroupBox(self.dockWidgetContents)
        self.areaboundarytable_groupbox.setObjectName(_fromUtf8("areaboundarytable_groupbox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.areaboundarytable_groupbox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.area_table_label = QtGui.QLabel(self.areaboundarytable_groupbox)
        self.area_table_label.setObjectName(_fromUtf8("area_table_label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.area_table_label)
        self.area_labelcolumn_label = QtGui.QLabel(self.areaboundarytable_groupbox)
        self.area_labelcolumn_label.setObjectName(_fromUtf8("area_labelcolumn_label"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.area_labelcolumn_label)
        self.area_geometrycoumn_label = QtGui.QLabel(self.areaboundarytable_groupbox)
        self.area_geometrycoumn_label.setObjectName(_fromUtf8("area_geometrycoumn_label"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.area_geometrycoumn_label)
        self.area_label_lineEdit = QtGui.QLineEdit(self.areaboundarytable_groupbox)
        self.area_label_lineEdit.setObjectName(_fromUtf8("area_label_lineEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.area_label_lineEdit)
        self.area_geometry_lineEdit = QtGui.QLineEdit(self.areaboundarytable_groupbox)
        self.area_geometry_lineEdit.setObjectName(_fromUtf8("area_geometry_lineEdit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.area_geometry_lineEdit)
        self.area_table_lineEdit_2 = QtGui.QLineEdit(self.areaboundarytable_groupbox)
        self.area_table_lineEdit_2.setObjectName(_fromUtf8("area_table_lineEdit_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.area_table_lineEdit_2)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout.addWidget(self.areaboundarytable_groupbox)
        self.DBConnection_dockable.setWidget(self.dockWidgetContents)
        self.verticalLayout_2.addWidget(self.DBConnection_dockable)

        self.retranslateUi(db_conn_QWidget)
        QtCore.QMetaObject.connectSlotsByName(db_conn_QWidget)

    def retranslateUi(self, db_conn_QWidget):
        db_conn_QWidget.setWindowTitle(_translate("db_conn_QWidget", "Form", None))
        self.DBConnection_dockable.setWindowTitle(_translate("db_conn_QWidget", "DB Connection", None))
        self.dbconFile_GroupBox.setTitle(_translate("db_conn_QWidget", "Configuration File", None))
        self.confi_LoadFile_pushButton.setText(_translate("db_conn_QWidget", "Load", None))
        self.config_saveFile_PushButton.setText(_translate("db_conn_QWidget", "Save", None))
        self.config_filename_lineEdit.setText(_translate("db_conn_QWidget", "dbcon.json", None))
        self.connection_groupbox.setTitle(_translate("db_conn_QWidget", "Connection", None))
        self.conn_host_label.setText(_translate("db_conn_QWidget", "Host", None))
        self.conn_port_label.setText(_translate("db_conn_QWidget", "Port", None))
        self.conn_UserFile_labl.setText(_translate("db_conn_QWidget", "user file", None))
        self.conn_dbname_label.setText(_translate("db_conn_QWidget", "database name", None))
        self.socialtable_groupbox.setTitle(_translate("db_conn_QWidget", "Social Table", None))
        self.social_tablename_label.setText(_translate("db_conn_QWidget", "table name", None))
        self.social_datacolumn_label.setText(_translate("db_conn_QWidget", "data column", None))
        self.social_timecolum_label.setText(_translate("db_conn_QWidget", "time column", None))
        self.social_usercolumn_label.setText(_translate("db_conn_QWidget", "user column", None))
        self.social_geometrycoloumn_label.setText(_translate("db_conn_QWidget", "geometry column", None))
        self.areaboundarytable_groupbox.setTitle(_translate("db_conn_QWidget", "Area Boundary Table", None))
        self.area_table_label.setText(_translate("db_conn_QWidget", "table name", None))
        self.area_labelcolumn_label.setText(_translate("db_conn_QWidget", "lable column", None))
        self.area_geometrycoumn_label.setText(_translate("db_conn_QWidget", "geometry column", None))

