# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\dbconn.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dbconn_dockable(object):
    def setupUi(self, dbconn_dockable):
        dbconn_dockable.setObjectName(_fromUtf8("dbconn_dockable"))
        dbconn_dockable.resize(269, 559)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dbconFile_GroupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.dbconFile_GroupBox.setObjectName(_fromUtf8("dbconFile_GroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dbconFile_GroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.config_LoadFile_pushButton = QtGui.QPushButton(self.dbconFile_GroupBox)
        self.config_LoadFile_pushButton.setAutoDefault(False)
        self.config_LoadFile_pushButton.setObjectName(_fromUtf8("config_LoadFile_pushButton"))
        self.horizontalLayout_2.addWidget(self.config_LoadFile_pushButton)
        self.config_saveFile_pushButton = QtGui.QPushButton(self.dbconFile_GroupBox)
        self.config_saveFile_pushButton.setObjectName(_fromUtf8("config_saveFile_pushButton"))
        self.horizontalLayout_2.addWidget(self.config_saveFile_pushButton)
        self.config_filename_lineEdit = QtGui.QLineEdit(self.dbconFile_GroupBox)
        self.config_filename_lineEdit.setMaxLength(80)
        self.config_filename_lineEdit.setObjectName(_fromUtf8("config_filename_lineEdit"))
        self.horizontalLayout_2.addWidget(self.config_filename_lineEdit)
        self.verticalLayout_2.addWidget(self.dbconFile_GroupBox)
        self.connection_groupbox = QtGui.QGroupBox(self.dockWidgetContents)
        self.connection_groupbox.setObjectName(_fromUtf8("connection_groupbox"))
        self.dbconConnect_GroupBox_3 = QtGui.QVBoxLayout(self.connection_groupbox)
        self.dbconConnect_GroupBox_3.setObjectName(_fromUtf8("dbconConnect_GroupBox_3"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.conn_host_label = QtGui.QLabel(self.connection_groupbox)
        self.conn_host_label.setObjectName(_fromUtf8("conn_host_label"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.conn_host_label)
        self.conn_host_lineEdit = QtGui.QLineEdit(self.connection_groupbox)
        self.conn_host_lineEdit.setObjectName(_fromUtf8("conn_host_lineEdit"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.conn_host_lineEdit)
        self.conn_port_label = QtGui.QLabel(self.connection_groupbox)
        self.conn_port_label.setObjectName(_fromUtf8("conn_port_label"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.conn_port_label)
        self.conn_port_lineEdit = QtGui.QLineEdit(self.connection_groupbox)
        self.conn_port_lineEdit.setObjectName(_fromUtf8("conn_port_lineEdit"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.conn_port_lineEdit)
        self.conn_UserFile_label = QtGui.QLabel(self.connection_groupbox)
        self.conn_UserFile_label.setObjectName(_fromUtf8("conn_UserFile_label"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.conn_UserFile_label)
        self.conn_dbname_label = QtGui.QLabel(self.connection_groupbox)
        self.conn_dbname_label.setObjectName(_fromUtf8("conn_dbname_label"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.conn_dbname_label)
        self.conn_userfilename_lineEdit = QtGui.QLineEdit(self.connection_groupbox)
        self.conn_userfilename_lineEdit.setObjectName(_fromUtf8("conn_userfilename_lineEdit"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.conn_userfilename_lineEdit)
        self.conn_dbname_lineEdit = QtGui.QLineEdit(self.connection_groupbox)
        self.conn_dbname_lineEdit.setObjectName(_fromUtf8("conn_dbname_lineEdit"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.conn_dbname_lineEdit)
        self.dbconConnect_GroupBox_3.addLayout(self.formLayout_5)
        self.verticalLayout_2.addWidget(self.connection_groupbox)
        self.socialtable_groupbox = QtGui.QGroupBox(self.dockWidgetContents)
        self.socialtable_groupbox.setObjectName(_fromUtf8("socialtable_groupbox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.socialtable_groupbox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.social_table_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_table_label.setObjectName(_fromUtf8("social_table_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.social_table_label)
        self.social_data_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_data_label.setObjectName(_fromUtf8("social_data_label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.social_data_label)
        self.social_data_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.social_data_lineEdit.setObjectName(_fromUtf8("social_data_lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.social_data_lineEdit)
        self.social_time_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_time_label.setObjectName(_fromUtf8("social_time_label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.social_time_label)
        self.social_time_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.social_time_lineEdit.setObjectName(_fromUtf8("social_time_lineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.social_time_lineEdit)
        self.social_user_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_user_label.setObjectName(_fromUtf8("social_user_label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.social_user_label)
        self.social_user_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.social_user_lineEdit.setObjectName(_fromUtf8("social_user_lineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.social_user_lineEdit)
        self.social_geom_label = QtGui.QLabel(self.socialtable_groupbox)
        self.social_geom_label.setObjectName(_fromUtf8("social_geom_label"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.social_geom_label)
        self.social_geom_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.social_geom_lineEdit.setObjectName(_fromUtf8("social_geom_lineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.social_geom_lineEdit)
        self.social_table_lineEdit = QtGui.QLineEdit(self.socialtable_groupbox)
        self.social_table_lineEdit.setObjectName(_fromUtf8("social_table_lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.social_table_lineEdit)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.socialtable_groupbox)
        self.areaboundarytable_groupbox = QtGui.QGroupBox(self.dockWidgetContents)
        self.areaboundarytable_groupbox.setObjectName(_fromUtf8("areaboundarytable_groupbox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.areaboundarytable_groupbox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.area_table_label = QtGui.QLabel(self.areaboundarytable_groupbox)
        self.area_table_label.setObjectName(_fromUtf8("area_table_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.area_table_label)
        self.area_table_lineEdit = QtGui.QLineEdit(self.areaboundarytable_groupbox)
        self.area_table_lineEdit.setObjectName(_fromUtf8("area_table_lineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.area_table_lineEdit)
        self.area_label_label = QtGui.QLabel(self.areaboundarytable_groupbox)
        self.area_label_label.setObjectName(_fromUtf8("area_label_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.area_label_label)
        self.area_label_lineEdit = QtGui.QLineEdit(self.areaboundarytable_groupbox)
        self.area_label_lineEdit.setObjectName(_fromUtf8("area_label_lineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.area_label_lineEdit)
        self.area_geom_label = QtGui.QLabel(self.areaboundarytable_groupbox)
        self.area_geom_label.setObjectName(_fromUtf8("area_geom_label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.area_geom_label)
        self.area_geom_lineEdit = QtGui.QLineEdit(self.areaboundarytable_groupbox)
        self.area_geom_lineEdit.setObjectName(_fromUtf8("area_geom_lineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.area_geom_lineEdit)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.verticalLayout_2.addWidget(self.areaboundarytable_groupbox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        dbconn_dockable.setWidget(self.dockWidgetContents)

        self.retranslateUi(dbconn_dockable)
        QtCore.QMetaObject.connectSlotsByName(dbconn_dockable)

    def retranslateUi(self, dbconn_dockable):
        dbconn_dockable.setWindowTitle(_translate("dbconn_dockable", "Database Connection", None))
        self.dbconFile_GroupBox.setTitle(_translate("dbconn_dockable", "Configuration File", None))
        self.config_LoadFile_pushButton.setText(_translate("dbconn_dockable", "Load", None))
        self.config_saveFile_pushButton.setText(_translate("dbconn_dockable", "Save", None))
        self.config_filename_lineEdit.setText(_translate("dbconn_dockable", "data\\db_defaultinfo.json", None))
        self.connection_groupbox.setTitle(_translate("dbconn_dockable", "Connection", None))
        self.conn_host_label.setText(_translate("dbconn_dockable", "Host", None))
        self.conn_port_label.setText(_translate("dbconn_dockable", "Port", None))
        self.conn_UserFile_label.setText(_translate("dbconn_dockable", "user file", None))
        self.conn_dbname_label.setText(_translate("dbconn_dockable", "database name", None))
        self.socialtable_groupbox.setTitle(_translate("dbconn_dockable", "Social Table", None))
        self.social_table_label.setText(_translate("dbconn_dockable", "table name", None))
        self.social_data_label.setText(_translate("dbconn_dockable", "data column", None))
        self.social_time_label.setText(_translate("dbconn_dockable", "time column", None))
        self.social_user_label.setText(_translate("dbconn_dockable", "user column", None))
        self.social_geom_label.setText(_translate("dbconn_dockable", "geometry column", None))
        self.areaboundarytable_groupbox.setTitle(_translate("dbconn_dockable", "Area Boundary Table", None))
        self.area_table_label.setText(_translate("dbconn_dockable", "table name", None))
        self.area_label_label.setText(_translate("dbconn_dockable", "lable column", None))
        self.area_geom_label.setText(_translate("dbconn_dockable", "geometry column", None))

