# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\topicmodel.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TopicModel_DockWidget(object):
    def setupUi(self, TopicModel_DockWidget):
        TopicModel_DockWidget.setObjectName(_fromUtf8("TopicModel_DockWidget"))
        TopicModel_DockWidget.resize(561, 511)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalGroupBox_3 = QtGui.QGroupBox(self.dockWidgetContents)
        self.verticalGroupBox_3.setObjectName(_fromUtf8("verticalGroupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Stoplist_listView = QtGui.QListView(self.verticalGroupBox_3)
        self.Stoplist_listView.setObjectName(_fromUtf8("Stoplist_listView"))
        self.verticalLayout_5.addWidget(self.Stoplist_listView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.stoplistLoad_pushButton = QtGui.QPushButton(self.verticalGroupBox_3)
        self.stoplistLoad_pushButton.setObjectName(_fromUtf8("stoplistLoad_pushButton"))
        self.horizontalLayout_2.addWidget(self.stoplistLoad_pushButton)
        self.stoplistSave_pushButton = QtGui.QPushButton(self.verticalGroupBox_3)
        self.stoplistSave_pushButton.setObjectName(_fromUtf8("stoplistSave_pushButton"))
        self.horizontalLayout_2.addWidget(self.stoplistSave_pushButton)
        self.stoplistFile_lineEdit = QtGui.QLineEdit(self.verticalGroupBox_3)
        self.stoplistFile_lineEdit.setObjectName(_fromUtf8("stoplistFile_lineEdit"))
        self.horizontalLayout_2.addWidget(self.stoplistFile_lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.verticalGroupBox_3)
        self.verticalGroupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.verticalGroupBox_2.setObjectName(_fromUtf8("verticalGroupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.verticalGroupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.verticalGroupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.verticalGroupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.verticalGroupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.verticalGroupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.topics_lineEdit = QtGui.QLineEdit(self.verticalGroupBox_2)
        self.topics_lineEdit.setObjectName(_fromUtf8("topics_lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.topics_lineEdit)
        self.words_lineEdit = QtGui.QLineEdit(self.verticalGroupBox_2)
        self.words_lineEdit.setObjectName(_fromUtf8("words_lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.words_lineEdit)
        self.passes_lineEdit = QtGui.QLineEdit(self.verticalGroupBox_2)
        self.passes_lineEdit.setObjectName(_fromUtf8("passes_lineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.passes_lineEdit)
        self.alpha_lineEdit = QtGui.QLineEdit(self.verticalGroupBox_2)
        self.alpha_lineEdit.setObjectName(_fromUtf8("alpha_lineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.alpha_lineEdit)
        self.update_lineEdit = QtGui.QLineEdit(self.verticalGroupBox_2)
        self.update_lineEdit.setObjectName(_fromUtf8("update_lineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.update_lineEdit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout.addWidget(self.verticalGroupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalGroupBox_21 = QtGui.QGroupBox(self.dockWidgetContents)
        self.verticalGroupBox_21.setObjectName(_fromUtf8("verticalGroupBox_21"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalGroupBox_21)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.runModel_pushButton = QtGui.QPushButton(self.verticalGroupBox_21)
        self.runModel_pushButton.setObjectName(_fromUtf8("runModel_pushButton"))
        self.horizontalLayout_3.addWidget(self.runModel_pushButton)
        self.stopModel_pushButton = QtGui.QPushButton(self.verticalGroupBox_21)
        self.stopModel_pushButton.setObjectName(_fromUtf8("stopModel_pushButton"))
        self.horizontalLayout_3.addWidget(self.stopModel_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.topicModelResults_treeWidget = QtGui.QTreeWidget(self.verticalGroupBox_21)
        self.topicModelResults_treeWidget.setObjectName(_fromUtf8("topicModelResults_treeWidget"))
        self.topicModelResults_treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.topicModelResults_treeWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.loadModel_pushButton = QtGui.QPushButton(self.verticalGroupBox_21)
        self.loadModel_pushButton.setObjectName(_fromUtf8("loadModel_pushButton"))
        self.horizontalLayout_4.addWidget(self.loadModel_pushButton)
        self.saveModel_pushButton = QtGui.QPushButton(self.verticalGroupBox_21)
        self.saveModel_pushButton.setObjectName(_fromUtf8("saveModel_pushButton"))
        self.horizontalLayout_4.addWidget(self.saveModel_pushButton)
        self.topicModelFile_lineEdit = QtGui.QLineEdit(self.verticalGroupBox_21)
        self.topicModelFile_lineEdit.setObjectName(_fromUtf8("topicModelFile_lineEdit"))
        self.horizontalLayout_4.addWidget(self.topicModelFile_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.verticalGroupBox_21)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        TopicModel_DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(TopicModel_DockWidget)
        QtCore.QMetaObject.connectSlotsByName(TopicModel_DockWidget)

    def retranslateUi(self, TopicModel_DockWidget):
        TopicModel_DockWidget.setWindowTitle(_translate("TopicModel_DockWidget", "Topic Modelling", None))
        self.verticalGroupBox_3.setTitle(_translate("TopicModel_DockWidget", "Stop Words", None))
        self.stoplistLoad_pushButton.setText(_translate("TopicModel_DockWidget", "Load ", None))
        self.stoplistSave_pushButton.setText(_translate("TopicModel_DockWidget", "Save", None))
        self.stoplistFile_lineEdit.setText(_translate("TopicModel_DockWidget", "stopwords.json", None))
        self.verticalGroupBox_2.setTitle(_translate("TopicModel_DockWidget", "Parameters", None))
        self.label.setText(_translate("TopicModel_DockWidget", "Topics", None))
        self.label_2.setText(_translate("TopicModel_DockWidget", "Words", None))
        self.label_3.setText(_translate("TopicModel_DockWidget", "Passes", None))
        self.label_4.setText(_translate("TopicModel_DockWidget", "Alpha", None))
        self.label_5.setText(_translate("TopicModel_DockWidget", "Update", None))
        self.topics_lineEdit.setText(_translate("TopicModel_DockWidget", "10", None))
        self.words_lineEdit.setText(_translate("TopicModel_DockWidget", "10", None))
        self.passes_lineEdit.setText(_translate("TopicModel_DockWidget", "5", None))
        self.alpha_lineEdit.setText(_translate("TopicModel_DockWidget", "0.01", None))
        self.update_lineEdit.setText(_translate("TopicModel_DockWidget", "0", None))
        self.verticalGroupBox_21.setTitle(_translate("TopicModel_DockWidget", "Topic Model", None))
        self.runModel_pushButton.setText(_translate("TopicModel_DockWidget", "Run Model", None))
        self.stopModel_pushButton.setText(_translate("TopicModel_DockWidget", "Stop Model", None))
        self.loadModel_pushButton.setText(_translate("TopicModel_DockWidget", "Load Model", None))
        self.saveModel_pushButton.setText(_translate("TopicModel_DockWidget", "Save Model", None))
        self.topicModelFile_lineEdit.setText(_translate("TopicModel_DockWidget", "topicmodel.json", None))

